networks:
  k6net:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6net
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=croco
      - INFLUXDB_ADMIN_PASSWORD=password1

  grafana:
    image: grafana/grafana:10.1.1
    networks:
      - k6net
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  k6:
    build: .
    networks:
      - k6net
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - .:/k6/project
    working_dir: /k6/project

volumes:
  influxdb-data: