networks:
  k6net_ui:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6net_ui
    ports:
      - "8088:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6_ui
      # - INFLUXDB_ADMIN_USER=croco
      # - INFLUXDB_ADMIN_PASSWORD=password1

  grafana:
    image: grafana/grafana:10.1.1
    networks:
      - k6net_ui
    ports:
      - "3002:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  k6:
    image: grafana/k6:master-with-browser
    # image: k6-with-dashboard
    networks:
      - k6net_ui
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6_ui
    volumes:
      - .:/k6/project
    working_dir: /k6/project

volumes:
  influxdb-data: