{
 "title": "k6 metrics tags",
 "description": "the same k6 dashboard but insteda of request urls, their tags or transaction names are used",
 "time": { "from": "2025-07-15T14:43:33.822Z", "to": "2025-07-15T14:44:39.442Z" },
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" },
   {
    "name": "testName",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(bucket: \"k6\", tag: \"testName\")"
   }
  ]
 },
 "panels": [
  { "title": "Errors stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\r\n  |> filter(fn: (r) => r[\"error\"] >=\"\")\r\n  |> count()\r\n  |> group()\r\n  |> rename(columns: {\"_value\":\"Errors found\", \"name\":\"requestUrl\"})\r\n  |> keep(columns: [\"requestUrl\", \"error\", \"error_code\", \"Errors found\"])"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sent bytes",
   "type": "stat",
   "description": "send bytes for the whole time of the test",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_sent\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "stat",
   "description": "received bytes for the whole time of the test",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_received\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Errors percentage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_count = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> sum()\r\n  |> rename(columns: {\"_value\": \"total_count\"})\r\n\r\n// Query to get error count\r\nerror_count = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_field\"])\r\n  |> sum()\r\n  |> rename(columns: {\"_value\": \"error_count\"})\r\n\r\n// Join the two queries on common fields and calculate error percentage\r\nerror_percentage = join(tables: {total: total_count, errors: error_count}, on: [\"_field\"])\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    error_percentage: (r.error_count / r.total_count) * 100.0\r\n  }))\r\n\r\nerror_percentage"
    }
   ]
  },
  {
   "title": "Overall throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: ${aggregation}s, fn: sum, createEmpty: false) \r\n  |> toFloat()\r\n  |> group()\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value /float(v: ${aggregation})) }))"
    }
   ]
  },
  {
   "title": "VUS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r._measurement == \"vus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> set(key: \"legend\", value: \"Active VUs\")              \r\n  |> keep(columns: [\"_time\", \"_value\", \"legend\"])           \r\n  |> group(columns: [\"legend\"])                             \r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\r\n  |> yield(name: \"Active VUs\")"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> set(key: \"legend\", value: \"Failed Requests\")           // добавляем тег\r\n  |> keep(columns: [\"_time\", \"_value\", \"legend\"])           // убираем всё лишнее\r\n  |> group(columns: [\"legend\"])                             // группируем по тегу legend\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"Failed Requests\")"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [\"legend\"])\r\n  |> set(key: \"legend\", value: \"Response Time (p95)\")\r\n  |> aggregateWindow(\r\n        every: v.windowPeriod,\r\n        fn: (tables=<-, column) => tables |> quantile(q: 0.95, method: \"exact_mean\"),\r\n        createEmpty: false\r\n    )\r\n  |> yield(name: \"Response Time (p95)\")"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 6s, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: r._value / 6.0}))\r\n  |> set(key: \"legend\", value: \"Requests per Second\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"legend\"])\r\n  |> group(columns: [\"legend\"])\r\n  |> yield(name: \"RPS\")"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Overall Throughput per request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"requestName\"])\r\n  |> aggregateWindow(every: ${aggregation}s, fn: count, createEmpty: false) \r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value /float(v: ${aggregation})) }))"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\" and r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: ${aggregation}s, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\r\n  |> rename(columns: {\"_value\": \"VUs\"})"
    }
   ]
  },
  {
   "title": "Overall Throughput per request (\"pass\")",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"status\"] >= \"200\" and  r[\"status\"] <= \"399\")\r\n  |> group(columns: [\"requestName\"])\r\n  |> aggregateWindow(every: ${aggregation}s, fn: count, createEmpty: false) \r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value /float(v: ${aggregation})) }))"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\" and r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\r\n  |> rename(columns: {\"_value\": \"VUs\"})"
    }
   ]
  },
  {
   "title": "Codes throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"status\"])\r\n  |> aggregateWindow(every: ${aggregation}s, fn: count, createEmpty: false)\r\n  |> keep(columns: [\"_value\", \"_time\", \"status\"])"
    }
   ]
  },
  { "title": "Network traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Received bytes per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "values= \r\nfrom(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"endpoint_data_recv\")\r\n    |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n\r\nurls= \r\nfrom(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"endpoint_data_recv\")\r\n    |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n\r\njoin(\r\n    tables: {urls,values},\r\n    on:[\"_time\"]\r\n    )\r\n\r\n|> rename(columns: {\"_value_urls\": \"url\",\"_value_values\":\"\"})\r\n|> keep(columns: [\"url\", \"_time\",\"\"])\r\n|> group(columns: [\"url\"])"
    }
   ]
  },
  {
   "title": "Sent bytes per request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "values= \r\nfrom(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"endpoint_data_sent\")\r\n    |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n\r\nurls= \r\nfrom(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"endpoint_data_sent\")\r\n    |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"url\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n\r\njoin(\r\n    tables: {urls,values},\r\n    on:[\"_time\"]\r\n    )\r\n\r\n|> rename(columns: {\"_value_urls\": \"url\",\"_value_values\":\"\"})\r\n|> keep(columns: [\"url\", \"_time\",\"\"])\r\n|> group(columns: [\"url\"])"
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Response times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"requestName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"requestName\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\" and r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\r\n  |> rename(columns: {\"_value\": \"VUs\"})\r\n "
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Summary k6",
   "type": "table",
   "description": "test dashboard (will be changed later) for k6-Grafana integration demo",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Avg\"})\r\n  |> keep(columns: [\"group_name\", \"Avg\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> count()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Count\"})\r\n  |> keep(columns: [\"group_name\", \"Count\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> min()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Min\"})\r\n  |> keep(columns: [\"group_name\", \"Min\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> max()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Max\"})\r\n  |> keep(columns: [\"group_name\", \"Max\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> median()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Med\"})\r\n  |> keep(columns: [\"group_name\", \"Med\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> quantile(q: 0.75)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"75%\"})\r\n  |> keep(columns: [\"group_name\", \"75%\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> quantile(q: 0.90)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"90%\"})\r\n  |> keep(columns: [\"group_name\", \"90%\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"group_name\"])\r\n  |> quantile(q: 0.95)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"95%\"})\r\n  |> keep(columns: [\"group_name\", \"95%\"])"
    },
    {
     "query": "tpsCalculator = () => {\r\ncount = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"group_name\"])\r\n  |> count()\r\n  |> toFloat()\r\n  |> group()\r\n  |> keep(columns: [\"_value\", \"group_name\"])\r\n\r\n integral = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"group_duration\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"group_name\"])\r\n  |> integral()\r\n  |> toFloat()\r\n  |> group() \r\n  |> keep(columns: [\"_value\", \"group_name\"])\r\n  \r\n  return join(\r\n      tables:{count:count, integral:integral},\r\n      on:[\"group_name\"]\r\n    )\r\n    |> map(fn:(r) => ({\r\n             group_name: r.group_name,\r\n             TPS: r._value_count / r._value_integral,\r\n             TPM: (r._value_count / r._value_integral) * 60.0,\r\n             TPH: (r._value_count / r._value_integral) * 60.0 * 60.0,        \r\n    }))       \r\n}\r\n\r\ntpsCalculator()"
    }
   ]
  },
  {
   "title": "Summary k6",
   "type": "table",
   "description": "test dashboard (will be changed later) for k6-Grafana integration demo",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Avg\"})\r\n  |> keep(columns: [\"name\", \"Avg\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> count()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Count\"})\r\n  |> keep(columns: [\"name\", \"Count\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> min()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Min\"})\r\n  |> keep(columns: [\"name\", \"Min\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> max()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Max\"})\r\n  |> keep(columns: [\"name\", \"Max\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> median()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Med\"})\r\n  |> keep(columns: [\"name\", \"Med\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> quantile(q: 0.75)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"75%\"})\r\n  |> keep(columns: [\"name\", \"75%\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> quantile(q: 0.90)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"90%\"})\r\n  |> keep(columns: [\"name\", \"90%\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> quantile(q: 0.95)\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"95%\"})\r\n  |> keep(columns: [\"name\", \"95%\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> stddev()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"stddev\"})\r\n  |> keep(columns: [\"name\", \"stddev\"])"
    },
    {
     "query": "tpsCalculator = () => {\r\ncount = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")  \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"name\"])\r\n  |> count()\r\n  |> toFloat()\r\n  |> group()\r\n  |> keep(columns: [\"_value\", \"name\"])\r\n\r\n integral = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\" and r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")  \r\n  |> group(columns: [\"name\"])\r\n  |> integral()\r\n  |> toFloat()\r\n  |> group() \r\n  |> keep(columns: [\"_value\", \"name\"])\r\n  \r\n  return join(\r\n      tables:{count:count, integral:integral},\r\n      on:[\"name\"]\r\n    )\r\n    |> map(fn:(r) => ({\r\n             name: r.name,\r\n             TPS: r._value_count / r._value_integral,\r\n             TPM: (r._value_count / r._value_integral) * 60.0,\r\n             TPH: (r._value_count / r._value_integral) * 60.0 * 60.0,        \r\n    }))       \r\n}\r\n\r\ntpsCalculator()"
    }
   ]
  },
  {
   "title": "Response times detailed",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Response time\"})\r\n  |> keep(columns: [\"name\", \"Response time\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Sending time\"})\r\n  |> keep(columns: [\"name\", \"Sending time\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Receive time\"})\r\n  |> keep(columns: [\"name\", \"Receive time\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"TTFB\"})\r\n  |> keep(columns: [\"name\", \"TTFB\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"TLS_handshake\"})\r\n  |> keep(columns: [\"name\", \"TLS_handshake\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"TCP Connect\"})\r\n  |> keep(columns: [\"name\", \"TCP Connect\"])"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.testName == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\" and r[\"_field\"] == \"value\")   \r\n  |> group(columns: [\"name\"])\r\n  |> mean()\r\n  |> group()\r\n  |> rename(columns: {\"_value\": \"Wait for TCP slot\"})\r\n  |> keep(columns: [\"name\", \"Wait for TCP slot\"])"
    }
   ]
  }
 ]
}